Excel example
dafnifacility/dafni-example-models pull request #24
Opened 2023-05-05 15:13 UTC by stevenkj1

2023-05-09 15:54 UTC, roseDickinson requested changes

2023-05-09 15:54 UTC, roseDickinson commented on ExcelExample-FrenchTraffic/Dockerfile
> +# ENV ISDOCK="Yes"
This line and the first and second should probably be deleted

2023-05-09 15:54 UTC, roseDickinson commented on ExcelExample-FrenchTraffic/main.py
> +if os.environ.get("ISDAFNI") == "True":
why not use the isDAFNI variable here?

also you can shorten this by using `os.getenv("ISDAFNI")` and optionally provide a second arg to be the default value e.g.: `os.getenv("ISDAFNI", False)`

2023-05-09 15:54 UTC, roseDickinson commented on ExcelExample-FrenchTraffic/main.py
> +        #for mnth in range(0, len(pdat.rmonths)):
commented code to remove?

2023-05-09 15:54 UTC, roseDickinson commented on ExcelExample-FrenchTraffic/main.py
> +        for yr in pdat.ryears: # Mv this to the class
Should the comment be removed?

There appear to be a lot of comments that could be removed

2023-05-09 15:54 UTC, roseDickinson commented on ExcelExample-FrenchTraffic/Dockerfile
> +# COPY BAAC_2021.xlsx . # /data/inputs
This line might need deleting too?

2023-05-10 12:19 UTC, stevenkj1 commented on ExcelExample-FrenchTraffic/Dockerfile
> +# ENV ISDOCK="Yes"
Removed all the excess commented out lines

2023-05-10 13:06 UTC, roseDickinson approved these changes

2023-05-10 13:07 UTC, merged